version: '3.8'
networks:
  homelibnetwork:
    driver: bridge

services:
  app:
    image: sqwezzy/nodejs2024q3-service
    restart: always
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - homelibnetwork
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    command: ["npm", "run", "migrate:start:dev"]

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: ["postgres", "-c", "logging_collector=true", "-c", "log_statement=all"]
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminuser -d homelibdb"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - homelibnetwork

volumes:
  postgres:
