version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT}:${PORT}"
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
